name: Reusable Test-Composite

on:
  workflow_call:
    inputs:
      env_file:
        type: string
        description: "path to .env file"
        required: false 
        default: ./.github/variables/myvars.env

jobs:
  
  env-variables:
    uses: RukayaTest/Test-Composite/.github/workflows/env-variable.yml@main
    with:
      var_file_path: ${{ inputs.env_file }}
  
  echo-env-variables:
    runs-on: ubuntu-latest
    needs: 
      - env-variables
    steps:
      - run: echo ${{ needs.env-variables.outputs.env_vars }}
    
  echo-secrets: 
    if: ${{ false }}  # disable for now
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
      
      - name: echo Environment Variables 
        run: echo "$ENV_CONTEXT"
        env:
          ENV_CONTEXT: ${{ toJson(env) }}
      
      - name: view the secrets context
        shell: bash
        run: echo "$SECRETS_CONTEXT"
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
